### ISSUE TITLE
Parameterize column names

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/deta#14]
I have a table with a few columns named similarly, and I want to pass a parameter to an expression to specify which column I want to use in the query. Here’s a naive example:

```racket
(define (list-articles type #:series [s #t] #:limit [lim -1] #:order [order 'desc])
  (define html-field (format "a.listing-~a-html" type))
  (~> (from article #:as a)
      (select (as ,html-field html)
              pub-field
              ser-field)
      (limit ,lim)
      (order-by ([published ,order]))
      (project-onto listing-schema)))
```

You can see why this won’t work; the value of the `html` column will always be the string contents of `html-field`, not the contents of the field it refers to:

```racket
> (lookup cache-conn (list-articles 'full #:series "test-series"))
(listing #<meta> "a.listing-full-html" #<date 2018-08-07> 'series/test-series.html)
> (list-articles 'full #:series "test-series")
(query "SELECT $1 AS html, a.published, a.series_page FROM articles AS a ORDER BY PUBLISHED DESC LIMIT $2" "a.listing-full-html" -1)
````

I have been able to do what I want by putting the entire query inside a macro:

```racket
(require (for-syntax racket/base syntax/parse racket/syntax))
(define-syntax (new-list-articles stx)
  (syntax-parse stx
    [(_ type
        (~optional (~seq #:series s) #:defaults ([s #'#t]))
        (~optional (~seq #:limit lim) #:defaults ([lim #'-1]))
        (~optional (~seq #:order order) #:defaults ([order #''desc])))
     (with-syntax ([html-field (format-id #'type "a.listing-~a-html" #'type)])
       #'(~> (from article #:as a)
             (select (as html-field html)
                     a.published
                     a.series-page)
             (limit ,lim)
             (order-by ([a.published ,order]))
             (project-onto listing-schema)))]))
```

Is this the best way to do this, or did I miss a simpler/better method?

**Comment by Bogdanp** [comment]
The (undocumented) `fragment` form can be used for this, but you'll have to depend on `deta/private/ast`. My plan is to eventually make `deta/private/ast` and `deta/private/query` public and a bunch of my own code already depends on them so they're unlikely to change. The problem is they're undocumented so you may have to dive into the code to figure out how they should be used.

Here's how I would implement your example using `fragment`:

```racket
#lang racket/base

(require deta
         (prefix-in ast: deta/private/ast)
         threading)

(define lim 10)
(define order 'asc)
(define html-field "a-dynamic-field")

(displayln
 (~> (from "articles" #:as a)
     (select (fragment (ast:as (ast:qualified "a" html-field)
                               "html"))
             a.published
             a.series-page)
     (limit ,lim)
     (order-by ([a.published ,order]))))
```

and that outputs:

```
#<query: SELECT a."a-dynamic-field" AS html, a.published, a.series_page FROM articles AS a ORDER BY a.published LIMIT $1 10>
```

**Comment by otherjoel** [comment]
This works nicely and feels lighter than my macro. I’ll stick with this for now!

**Comment by yurkobb** [comment]
> My plan is to eventually make deta/private/ast and deta/private/query public and a bunch of my own code already depends on them so they're unlikely to change.

That'd be great! I would suggest also making `make-entity-instance` [from `deta/query.rkt`](https://github.com/Bogdanp/deta/blob/master/deta-lib/query.rkt#L232) public as well; that would probably make it easier to construct entities based on queries `join`ining several entities.

**Comment by Bogdanp** [comment]
@yurkobb can you give an example of how you would use `make-entity-instance` to join things?  That function in particular feels very specialized (in particular because it has to deal with dialects) so I'd rather not expose it, but there might be a simpler version of it that we could expose.

**Comment by yurkobb** [comment]
Sure!

I think this boils down to the ability to programmatically construct and deconstruct entities - be it a slice of a row of columns resulting from a composite query joining together multiple tables or a (validated) json payload received from a client.

Currently, in order to create an instance programmatically from a list (or hash) of fields I have to use `keyword-apply` (which requires the keywords to be sorted in a different order than the fields in the struct).

<s>if I could use a function that I could `apply` onto a slice of a result row</s> (sorry, forget the apply bit), maybe something like:

```racket
(define q ...) ; some query with a join
(for/list ([row (query-rows (db-conn) q)])
  (define the-product-i18n (list->entity product-i18n (row-slice row product product-i18n)))
  (define the-product (list->entity product (append (row-slice row product) (list product-i18n))))
  ...)
```

`row-slice` would be a function returning a slice of a row corresponding to the last entity in the argument list.

Also, the other way around - decomposing an entity into some key-value structure could make it easier to write polymorphic code for serialization.

In my case the i18n bit would repeat for all the key schemas (for instance images with alt text themselves associated to a product), that's why I'm trying to abstract that out into something that I could reuse over multiple schemas.

**Comment by yurkobb** [comment]
(I've edited the example a bunch of times, sorry for the confusion).

**Comment by Bogdanp** [comment]
I see what you mean now and I agree that `make-entity-instance` should become public to support use cases like that one. I might want to make its `dialect` argument optional and add a `current-dialect` parameter before doing that, though. I'll think about that for a bit. 

Re. going the other way around, I don't see an issue with adding an `entity->hash` function, or even potentially supporting `gen:dict` on the `entity` struct, like you mentioned.
