### ISSUE TITLE
order-by doesn't allow dynamic values

### ISSUE THREAD

**Issue by euhmeuh** [Bogdanp/deta#2]
I tried making a query using `(order-by)`, but the parameters `#:asc` and `#:desc` are syntax-based, so I can't have a function that takes an argument, say `direction`, and have the query changed depending on `direction`'s value.

Something like:
```racket
(define (get-pirates db #:order-by [order? #f]
                        #:direction [dir? #f])
  (define order (and order?))
  (define direction (and dir?))
  (for/list ([p (in-entities db (~> (from pirate #:as p)
                                    (order-by ([p.order direction]))))])
    p))
```

By reading deta's code, I can see macros expand to usage of dynamic functions (like `dyn:order-by`), but they don't seem to be publicly accessible.

Any plans to provide dynamic equivalents of `order-by` and other syntaxes?

**Comment by Bogdanp** [comment]
I would say it's fairly safe to refer to stuff inside `deta/private/query` specifically. They'll eventually be exported publicly most likely unchanged or with minimal, documented, changes.  My own production application depends on that module in a couple places.

We could also add an additional pattern to `q-order-pair` to support an arbitrary expression for the direction since the contract for the private version of `order-by` will catch any runtime issues.  I'd happily accept such a change if you'll PR it, otherwise I can do it myself sometime in the next few weeks. My preference would be for the following syntax:

```racket
(~> (from pirate #:as p)
    (order-by ([p.order ,direction])))
```

Regarding

> Any plans to provide dynamic equivalents of order-by and other syntaxes?

deta does everything I need right now and I only add new stuff as the need arises, but I'll gladly accept contributions for anything that makes sense/that folks need. The only thing I ask is to bring it up in an issue first (like you've done here!) before making a PR.

**Comment by euhmeuh** [comment]
Thanks for your answer! I didn't delve enough into your code to see exactly what to change, so I reverted back to using my own SQL query maker that supports that feature (alas not as elegantly as deta). I'd really like to migrate all my code to deta, so I'll see if I have some time to work a bit on this and make a PR.

As I see it, there's two features to enable:
1. Allow a dynamic direction.
2. Allow a dynamic field to order by.

Your suggestion for the first point seems good, but I have a hard time figuring out how to use the same technique with the second point.
I didn't check what the dot notation expands to, but I guess an alternative notation could be:
```racket
(~> (from pirate #:as p)
    (order-by ([(dot p ,order) ,direction])))
```
_*Could also be `(field p ,order)`._

What do you think?

**Comment by Bogdanp** [comment]
The `column` in an order-by pair can be [any query expression](https://github.com/Bogdanp/deta/blob/3c0c4bfc23583fce1b0e4f4695707ee701f8d4e4/deta-lib/query.rkt#L358) (`q-expr`s are defined [here](https://github.com/Bogdanp/deta/blob/3c0c4bfc23583fce1b0e4f4695707ee701f8d4e4/deta-lib/query.rkt#L303)).  So, to make it possible to reference columns dynamically, you can add a new pattern to `q-expr` like the `(field p (unquote e))` you mentioned (though, maybe `column` (or even `ref`?) would be more appropriate than `field`), where `e` can be any expression that evaluates to a string.  This would prove useful in the other forms as well so I'm all for it.

**Comment by euhmeuh** [comment]
Great! I'm all set then, I'll try putting something together.

**Comment by euhmeuh** [comment]
I didn't got the time to work on it in the end, sorry. Thanks for your work on this!

**Comment by Bogdanp** [comment]
No worries at all! I happened to need this yesterday so that's why I went ahead and did it. :D
