### ISSUE TITLE
Must select fields in order when using project-onto

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/deta#20]
I found out today that when using `project-onto` with a “virtual” schema, the columns must be `select`ed in precisely the same order as they are specified in the virtual schema’s `define-schema` definition. The query attempts to assign the values in this order without reference to the column names; if the field types do not match, you’ll see errors; if they do match, then no error is given but the “getter” functions on the returned structs will give you the wrong values.

I don’t know if this is the expected behavior that everyone except me knew about already, or if it is a subtlety that would just be worth including in the documentation, or if it is actually a bug.

**Comment by Bogdanp** [comment]
It's funny because I got bit by this exact thing the other day. This is the intended behavior but it's not great. I think I had a good reason to do it this way, but I don't remember exactly what it was so I'll take another look at this this weekend and see if I can't make it auto-select.

**Comment by Bogdanp** [comment]
I finally took a look at this today. The reason I didn't make it automatically select initially is because, at the time the projection gets applied, it's not currently possible to determine whether or not a custom selection was already made so it would be unsafe to override it.  I think I'm going to keep the current behavior for now and just update the documentation to mention the drawback.
