### ISSUE TITLE
[Question] Use with North

### ISSUE THREAD

**Issue by pmatos** [Bogdanp/deta#25]
Hi Bogdan,

In the documentation you mention the following: `While the DDL functionality is convenient for the purposes of this tutorial, in real world projects you should probably use something like north to manage your database table schemas.`

However, I am using `deta` because I really don't want to know how things are layed out in the DB. North seems to require me to know how tables are built. Therefore it seems that I would have to sort of break the abstraction created by `deta` to use `north` to manage my schemas.

I am slightly confused how to use them to cooperate with each other. Do you have an example that I can look at?

**Comment by Bogdanp** [comment]
Hi Paulo,

You're right that `north` requires you to know the details of your DB and tables and there's currently no way around that.  For me, that's not a problem because I want to be aware of those details in my applications and deta is just a thin abstraction on top of the DB.

Deta schemas have enough information on them that someone could take that metadata and build a tool to automatically generate north migrations or migrations in some higher-level DSL (like Django or Rails' migrations) and I'd be happy to change deta if necessary to help facilitate that, but it's not something I'm likely to build myself.

**Comment by pmatos** [comment]
Thanks
