### ISSUE TITLE
group-by: name collision with racket/list

### ISSUE THREAD

**Issue by yurkobb** [Bogdanp/deta#33]
I'm not sure if this is really a problem, mere an inconvenience:

test.rkt:

```racket
#lang racket/base

(require deta
         racket/list)
```

```shell
$ racket test.rkt
test.rkt:4:9: module: identifier already required
  at: group-by
  in: racket/list
  also provided by: deta
  location...:
   test.rkt:4:9
  context...:
   do-raise-syntax-error
   check-not-defined
   for-loop
   [repeats 1 more time]
   perform-require!
   for-loop
   finish
   [repeats 2 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module
   expand-capturing-lifts
   temp98_0
   temp71_0
   compile
   temp65_0
   ...
```

I've been doing `(require (only-in racket/list ...)` to work around this. I guess sacrificing group-by in deta is an option, so maybe we can add a note to the docs for newbie like me? :)

As a side note, it only happens when requiring racket/list explicitly, but not in `#lang racket`, where bindings from racket/list are provided automatically (I'm not sure why).

**Comment by Bogdanp** [comment]
> As a side note, it only happens when requiring racket/list explicitly, but not in #lang racket, where bindings from racket/list are provided automatically (I'm not sure why).

Shadowing is generally allowed because it's assumed that you want the binding from the imported module over what's already in the language, but when two modules conflict it's unclear which one should win out so an error is raised instead. 

Using `only-in`, `except-in` or `prefix-in` is the right approach here.  Adding a note about that to the documentation of `group-by` sounds like a good idea. Feel free to spin up a PR if you feel like it.
